### PR TITLE
bug fix: stale rev still updates

### LINKED ISSUE #58: update failed in perf test run: panic with "store.keyindex: put with unexpected smaller Revision"
this happens in perf test (go-ycsb run); not always; occasionally 1 out of per run (1000 ops)

## How to reproduce:
1. start rkv
2. modify go-ycsb code pointing to the started rkv
3. run go-ycsb load + run
```bash
./bin/go-ycsb load rkv -P workload/workloada
./bin/go-ycsb run rkv -P workload/workloada
```
notice rn command might yield an UOPDATE_ERROR sometimes.

### PR DESCRIPTION
**Pull request by h-w-chen**
this PR fixes #58 

stale updates are still allowed - not treated as failure; but the latest modified and generation version intact (not to be affected), so that getting the latest value would always return the newest rev.

it comes with a unit test to ensure such behavior.

### CODE REVIEW

**Review by pdgetrf — APPROVED** [review]
LGTM

File: pkg/index/key_index.go [hunk 1]
```diff
@@ -59,24 +60,41 @@ type keyIndex struct {
...
 	}
-	g.revs = append(g.revs, rev)
-	g.ver++
-	ki.modified = rev
+
+	if !rev.GreaterThan(ki.modified) {
+		klog.Warningf("rev %v is older than the existing latest rev %v", rev, ki.modified)
+		// older than existent revs; locate its position in order
+		var i int
+		for i = len(g.revs) - 1; i >= 0; i-- {
```
Comment (jshaofuturewei) [inline pkg/index/key_index.go:79]: The revs are sorted. Not sure why u need to compare each of them.

**Comment by jshaofuturewei** [comment]
Are the changes to handle concurrent putting?

The comment is confusing since it removes the previous panic without adding errors. Therefore, users don't know if the index tree is updated or not.

File: pkg/index/key_index.go (hunk 1 above)
Comment (jshaofuturewei) [reply pkg/index/key_index.go:79]: I remember the change is to adopt to multiple threads completing for updates. Therefore, if two threads are updating the the revision list. The origin one is [1, 2, 5]. The two threads get the same list. The one with rev 3 first update the list to [1,2,3,5]. Then the one with rev 4 know the position to insert is 2 and then the rev is changed to [1,2,4,3,5]?

Comment (h-w-chen) [reply pkg/index/key_index.go:79]: index should have lock to protect such corruption happen

Comment (jshaofuturewei) [reply pkg/index/key_index.go:79]: I got it. I found there was a RW lock. My another concern is whether we can write to the PAST. Considering we might have a index cluster for HA in the future. Do we need to sync the old versions to other nodes?

**Comment by h-w-chen** [comment]
for now this will be checked in. However, if in the future this stale-update-allowed approach lead to bugs in application or other server components, we will take other approach to err the stale update.
